### ISSUE TITLE
[15.0.1] Error parsing crafting recipe?

### ISSUE THREAD

**Issue by embeddedt** [CodeMouse92/no-monster-minecraft#4]
I'm trying to use your plugin on a Paper 1.15-based server. I made sure to checkout the 1.15 version and not the 1.16 version (for reference, the commit hash I'm using is `8feab9e70df0892bc2f5cdc9838453c1a40a74fc`).

When the server starts I get the following error:

```
[15:10:28 ERROR]: Parsing error loading recipe no-monster:crafting/red_sand                                                                        
com.google.gson.JsonSyntaxException: Missing key, expected to find a JsonObject                                                                    
        at net.minecraft.server.v1_15_R1.ChatDeserializer.t(SourceFile:402) ~[paper-1.15.2.jar:git-Paper-"013374629"]                              
        at net.minecraft.server.v1_15_R1.ShapedRecipes$a.a(ShapedRecipes.java:330) ~[paper-1.15.2.jar:git-Paper-"013374629"]                       
        at net.minecraft.server.v1_15_R1.ShapedRecipes$a.a(ShapedRecipes.java:323) ~[paper-1.15.2.jar:git-Paper-"013374629"]                       
        at net.minecraft.server.v1_15_R1.CraftingManager.a(CraftingManager.java:145) ~[paper-1.15.2.jar:git-Paper-"013374629"]                     
        at net.minecraft.server.v1_15_R1.CraftingManager.a(CraftingManager.java:53) ~[paper-1.15.2.jar:git-Paper-"013374629"]                      
        at net.minecraft.server.v1_15_R1.CraftingManager.a(CraftingManager.java:27) ~[paper-1.15.2.jar:git-Paper-"013374629"]                      
        at net.minecraft.server.v1_15_R1.ResourceDataAbstract.a(SourceFile:13) ~[paper-1.15.2.jar:git-Paper-"013374629"]  
```

Is there anything else I need to set up?

**Comment by CodeMouse92** [comment]
Nope, that's an error on my end. I'm fixing it in the next release. In the meantime, you can patch it yourself by replacing `red_sand.json` with the one here: https://github.com/CodeMouse92/the-missing-recipes/blob/main/data/minecraft/recipes/crafting/red_sand.json

**Comment by embeddedt** [comment]
Thanks for the quick reply; the replacement file worked without problems. Glad to see I'm not the only person who prefers peaceful mode. :slightly_smiling_face:

**Comment by CodeMouse92** [comment]
This should be resolved now in the latest release.

For 1.15, download [No Monster Minecraft v15.2.1](https://github.com/CodeMouse92/no-monster-minecraft/releases/tag/v15.2.1) and, if desired, [The Missing Recipes v15.2.0](https://github.com/CodeMouse92/the-missing-recipes/releases/tag/v15.2.0). Red Sand and most non-mob-related recipes were moved to The Missing Recipes.
